=== avinashvenkateswarlu/publicfiles/story.xsd
<?xml version="1.0"?>
<!-- To change this license header, choose License Headers in Project Properties. 
	To change this template file, choose Tools | Templates and open the template 
	in the editor. -->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="story">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="narrative" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="testcase" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="scenario" minOccurs="1" type="xs:string"
								maxOccurs="1" />
							<xs:element name="meta-data" minOccurs="1" type="metatype"
								maxOccurs="unbounded" />
							<xs:element name="steps" type="steps" maxOccurs="1"
								minOccurs="1" />
							<xs:element name="examples" type="xs:string"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:complexType name="metatype">
		<xs:attribute name="testcase-id" type="xs:string" use="required" />
		<xs:attribute name="module-id" type="xs:string" use="required" />
		<xs:attribute name="description" type="xs:string" use="required" />
	</xs:complexType>


	<xs:complexType name="steps">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="step">
				<xs:complexType>
					<xs:choice minOccurs="0" maxOccurs="1">
						<xs:element name="Parameters">
							<xs:complexType>
								<xs:choice minOccurs="1" maxOccurs="unbounded">
									<xs:element name="parameter">
										<xs:complexType>
											<xs:attribute name="name" use="required" />
											<xs:attribute name="value" use="optional" />
										</xs:complexType>
									</xs:element>
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:choice>
					<xs:attribute name="action" type="actions" use="required"></xs:attribute>
					<xs:attribute name="control" type="controls" use="required"></xs:attribute>
					<xs:attribute name="control-name" type="xs:string"
						use="required"></xs:attribute>
					<xs:attribute name="parameter" type="xs:string" use="optional" />
					<xs:attribute name="type" type="steptype" use="required" />
				</xs:complexType>
			</xs:element>
			<!-- <xs:element name="When">
				<xs:complexType>
					<xs:choice>
						<xs:element name="Parameters">
							<xs:complexType>
								<xs:choice minOccurs="1" maxOccurs="unbounded">
									<xs:element name="parameter">
										<xs:complexType>
											<xs:attribute name="name" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:choice>
					<xs:attribute name="action" type="actions" use="required"></xs:attribute>
					<xs:attribute name="control" type="controls" use="required"></xs:attribute>
					<xs:attribute name="control-name" type="xs:string"
						use="required"></xs:attribute>
					<xs:attribute name="parameter" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Then">
				<xs:complexType>
					<xs:choice>
						<xs:element name="Parameters">
							<xs:complexType>
								<xs:choice minOccurs="1" maxOccurs="unbounded">
									<xs:element name="parameter">
										<xs:complexType>
											<xs:attribute name="name" use="required" />
										</xs:complexType>
									</xs:element>
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:choice>
					<xs:attribute name="action" type="actions" use="required"></xs:attribute>
					<xs:attribute name="control" type="controls" use="required"></xs:attribute>
					<xs:attribute name="control-name" type="xs:string"
						use="required"></xs:attribute>
					<xs:attribute name="parameter" type="xs:string" use="optional" />
				</xs:complexType>
			</xs:element> -->
		</xs:choice>
	</xs:complexType>

	<xs:simpleType name="actions">
		<xs:restriction base="xs:string">
			<xs:enumeration value="clicks"></xs:enumeration>
			<xs:enumeration value="verifies"></xs:enumeration>
			<xs:enumeration value="enters"></xs:enumeration>
			<xs:enumeration value="swipes"></xs:enumeration>
			<xs:enumeration value="selects"></xs:enumeration>
			<xs:enumeration value="validates"></xs:enumeration>
			<xs:enumeration value="swipeswithclick"></xs:enumeration>
			<xs:enumeration value="closes"></xs:enumeration>
			<xs:enumeration value="waits"></xs:enumeration>
                        <xs:enumeration value="clickcoordinates"></xs:enumeration>
                        <xs:enumeration value="gettext"></xs:enumeration>
                        <xs:enumeration value="nativepopuppassword"></xs:enumeration>
                        <xs:enumeration value="nativepopupusername"></xs:enumeration>
                        <xs:enumeration value="switchtochildframe"></xs:enumeration>
                        <xs:enumeration value="switchtochildpopup"></xs:enumeration>
                        <xs:enumeration value="rightclick"></xs:enumeration>
                        <xs:enumeration value="switchtoparentframe"></xs:enumeration>
                        <xs:enumeration value="switchtoparentpopup"></xs:enumeration>
                        <xs:enumeration value="switchtotab"></xs:enumeration>
                        <xs:enumeration value="switchtotab"></xs:enumeration>
			<xs:enumeration value="navigate"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="controls">
		<xs:restriction base="xs:string">
			<xs:enumeration value="button"></xs:enumeration>
			<xs:enumeration value="screen"></xs:enumeration>
			<xs:enumeration value="icon"></xs:enumeration>
			<xs:enumeration value="textfield"></xs:enumeration>
			<xs:enumeration value="page"></xs:enumeration>
			<xs:enumeration value="message"></xs:enumeration>
			<xs:enumeration value="dropdown"></xs:enumeration>
			<xs:enumeration value="browser"></xs:enumeration>
			<xs:enumeration value="web"></xs:enumeration>
			<xs:enumeration value="lable"></xs:enumeration>
			<xs:enumeration value="element"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="steptype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Given"></xs:enumeration>
			<xs:enumeration value="When"></xs:enumeration>
			<xs:enumeration value="Then"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== avinashvenkateswarlu/publicfiles/samplestory.xml
<?xml version="1.0" encoding="UTF-8"?>
<story name="Addfunds" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/avinashvenkateswarlu/publicfiles/master/story.xsd">
	<narrative>
In order to verify Addfunds game
As a Users
I want to verify Addfunds game
	</narrative>
	<testcase>
		<scenario>
			The intent of the test case is to verify whether  Missing_Information,Inadequate_Funds wager is displaying as per wireframe or not.
		</scenario>
		<meta-data testcase-id="19184" module-id="Missing _Information"
			description="MOB-015-EF-01 Missing Information for Transfer" />
		<meta-data testcase-id="19185" module-id="Inadequate_Funds"
			description="MOB-015-EF-02 Inadequate Funds for Transf" />
		
		<steps>
			<step type="Given" control-name="login" action="clicks"
				control="button" />
				
			<step type="When" control-name="&lt;parameters_emalid&gt;"
				action="enters" control="textfield">
			</step>
			<step type="When" control-name="submit" action="clicks"
				control="button">
			</step>

			<step type="Then" control-name="" action="validates" control="textfield">
				<Parameters>
					<parameter name="parameters1_emailid" />
					<parameter name="parameters2_valiedFormate" />
					<parameter name="parameters3_Erroralert" />
					<parameter name="length" value=">10" />
				</Parameters>
			</step>
			
			<step type="When" control-name="" action="swipes" control="icon">
				<Parameters>
				<parameter name="parameters1_direction"/>
				<parameter name="parameters2_offset"/>
				</Parameters>
			</step>
			
			<step type="When" control-name="login" action="verifies" control="page" />
			
			<step type="When" control-name="dropdown" action="clicks" control="button"></step>
			
			<step type="When" control-name="" action="selects" control="dropdown">
				<Parameters>
				<parameter name="parameters1_Androidid"/>
				<parameter name="parameters2_Text"/>
				<parameter name="parameters3_IOSid"/>
				<parameter name="parameters4_IOSDragid"/>
				<parameter name="parameters5_IOStextid"/>
				<parameter name="parameters6_Andriod"/>
				<parameter name="parameters7_AndriodTapid"/>
				</Parameters>
			</step>
		</steps>
		
		<examples>
|parameters1_emalid|parameters2_valiedFormate|parameters3_Erroralert|
|prabha@igt.com|afdsgsdfga|text=Please enter a valid Email address.|
|prabha@igt.com|sdhg@|
|prabha@igt.com|12334|
|prabha@igt.com||
|prabha@igt.com|prabha@igt.com|
		</examples>
	</testcase>
</story>
